import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { chmod, mkdir, mkdtemp, readFile, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { resolve } from 'node:path';
import test from 'node:test';
import { validateReadiness } from '../readiness/gate.mjs';
import { buildInjection } from '../failure-injection/control.mjs';
import { projectEvidence } from '../evidence/project.mjs';
import { verifyEvidence } from '../evidence/verify.mjs';

const sha = (value) => createHash('sha256').update(value).digest('hex');
test('readiness fails closed for missing required check and digest mismatch', () => { const document = { documentVersion:'1.0.0', component:'reservation-core', status:'READY', contractGraphSha256:'a'.repeat(64), checks:[] }; assert.ok(validateReadiness(document, 'b'.repeat(64)).length >= 3); });
test('failure injection is allowlisted and deterministic', () => { assert.deepEqual(buildInjection({ action:'kill', service:'postgres' }), ['compose','--project-name','tablekeeper-c2','kill','--signal','KILL','postgres']); assert.throws(() => buildInjection({ action:'exec', service:'postgres' }), /unsupported action/); assert.throws(() => buildInjection({ action:'kill', service:'evidence-projector' }), /unsupported service/); });
test('compose denies public database exposure and evidence networking', async () => { const text = await readFile(new URL('../compose.c2.yaml', import.meta.url), 'utf8'); assert.match(text, /internal: true/); assert.match(text, /ports: \[\]/); assert.match(text, /evidence-projector:[\s\S]*network_mode: none/); assert.doesNotMatch(text.match(/evidence-projector:[\s\S]*?(?=\nnetworks:)/)?.[0] ?? '', /secrets:/); assert.match(text, /pull_policy: never/); });
test('projection verifies digests, prefixes paths, and retains immutable output', async () => { const root = await mkdtemp(resolve(tmpdir(), 'c2a-')); const staging=resolve(root,'staging'); const output=resolve(root,'final'); await mkdir(resolve(staging,'raw'),{recursive:true}); const bytes='{"ok":true}\n'; await writeFile(resolve(staging,'raw/assertion.json'),bytes); const digest=sha(bytes); await writeFile(resolve(staging,'artifact-candidates.json'),JSON.stringify({documentVersion:'1.0.0',candidates:[{path:'raw/assertion.json',sha256:digest,mediaType:'application/json'}]})); await writeFile(resolve(staging,'test-execution-candidates.json'),JSON.stringify({documentVersion:'1.0.0',candidates:[{testId:'core.test',testDefinitionDigest:'sha256:'+'1'.repeat(64),executionId:'00000000-0000-4000-8000-000000000001',startedAt:'2026-09-30T00:00:00Z',finishedAt:'2026-09-30T00:00:01Z',result:'PASS',artifactPaths:['raw/assertion.json']}]})); await projectEvidence({staging,output,environmentDigest:'2'.repeat(64)}); const result=await verifyEvidence(output); assert.equal(result.result,'PASS'); const projected=JSON.parse(await readFile(resolve(output,'test-execution-evidence.json'),'utf8')); assert.deepEqual(projected[0].artifactPaths,['raw/proofs/raw/assertion.json']); assert.equal(projected[0].testDefinitionDigest,'sha256:'+'1'.repeat(64)); assert.equal(projected[0].environmentDigest,'sha256:'+'2'.repeat(64)); await chmod(output,0o755); });
test('projection rejects path traversal', async () => { const root = await mkdtemp(resolve(tmpdir(), 'c2a-bad-')); const staging=resolve(root,'staging'); await mkdir(staging); await writeFile(resolve(staging,'artifact-candidates.json'),JSON.stringify({documentVersion:'1.0.0',candidates:[{path:'../escape',sha256:'0'.repeat(64),mediaType:'text/plain'}]})); await writeFile(resolve(staging,'test-execution-candidates.json'),JSON.stringify({documentVersion:'1.0.0',candidates:[]})); await assert.rejects(projectEvidence({staging,output:resolve(root,'out'),environmentDigest:'2'.repeat(64)}),/invalid artifact candidate/); });
