// generated from schema sha256:f797a887e30fbea51bcb63bb8939a9515352bb76b5e3b14edb8e63b10ed9ecfb; DO NOT EDIT
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/availability/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["searchAvailability"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reservation-preparations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["prepareReservation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reservations:confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["confirmReservation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reservations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getReservation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reservations/{id}:modify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["modifyReservation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reservations/{id}:cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cancelReservation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ContractRef: {
            contractId: string;
            contractVersion: string;
        };
        /** Format: uuid */
        Uuid: string;
        /** Format: date-time */
        Instant: string;
        Actor: {
            /** @enum {unknown} */
            actorType: "GUEST" | "STAFF" | "MANAGER" | "SYSTEM";
            actorId: string;
        };
        QueryEnvelope: {
            contract: components["schemas"]["ContractRef"];
            tenantId: components["schemas"]["Uuid"];
            queryId: components["schemas"]["Uuid"];
            correlationId: components["schemas"]["Uuid"];
            issuedAt: components["schemas"]["Instant"];
            actor: components["schemas"]["Actor"];
            queryType: string;
            parameters: Record<string, never>;
        };
        /** @description Half-open interval [start,end) */
        TimeRange: {
            start: components["schemas"]["Instant"];
            end: components["schemas"]["Instant"];
        };
        AvailabilitySearchParameters: {
            venueId: components["schemas"]["Uuid"];
            partySize: number;
            requestedRange: components["schemas"]["TimeRange"];
        };
        AvailabilitySearchRequest: components["schemas"]["QueryEnvelope"] & {
            contract?: {
                /** @constant */
                contractId: "C03";
                /** @constant */
                contractVersion: "2.0.0";
            };
            /** @constant */
            queryType?: "SEARCH_AVAILABILITY";
            parameters?: components["schemas"]["AvailabilitySearchParameters"];
        };
        AtomicResource: {
            resourceId: components["schemas"]["Uuid"];
            /** @constant */
            resourceType: "TABLE";
        };
        AllocationCandidate: {
            candidateId: components["schemas"]["Uuid"];
            resources: components["schemas"]["AtomicResource"][];
            timeRange: components["schemas"]["TimeRange"];
            /** @constant */
            advisory: true;
            observedAt: components["schemas"]["Instant"];
        };
        AvailabilityResult: {
            tenantId: components["schemas"]["Uuid"];
            venueId: components["schemas"]["Uuid"];
            candidates: components["schemas"]["AllocationCandidate"][];
            /** @constant */
            authoritativeAtCommitOnly: true;
        };
        Error: {
            /** @enum {unknown} */
            code: "VALIDATION_FAILED" | "AUTH_REQUIRED" | "AUTH_FORBIDDEN" | "TENANT_SCOPE_VIOLATION" | "NOT_FOUND" | "PRECONDITION_REQUIRED" | "CONFLICT_ALLOCATION" | "CONFLICT_STATE" | "STALE_VERSION" | "STALE_RESOURCE_SNAPSHOT" | "IDEMPOTENCY_KEY_REUSED" | "TOKEN_INVALID" | "TOKEN_EXPIRED" | "TOKEN_SCOPE_MISMATCH" | "TOKEN_CONSUMED" | "POLICY_VERSION_NOT_FOUND" | "TERMS_NOT_ACCEPTED" | "CONTRACT_VERSION_UNSUPPORTED" | "CAPABILITY_UNAVAILABLE" | "DEPENDENCY_UNAVAILABLE" | "PLAN_INVALID" | "PLAN_STALE" | "PLAN_APPROVAL_REQUIRED" | "INTERNAL";
            message: string;
            retryable: boolean;
            correlationId: components["schemas"]["Uuid"];
            details?: {
                [key: string]: unknown;
            };
        };
        CommandEnvelope: {
            contract: components["schemas"]["ContractRef"];
            tenantId: components["schemas"]["Uuid"];
            commandId: components["schemas"]["Uuid"];
            idempotencyKey: string;
            correlationId: components["schemas"]["Uuid"];
            issuedAt: components["schemas"]["Instant"];
            actor: components["schemas"]["Actor"];
            commandType: string;
            expectedVersion?: number;
            payload: Record<string, never>;
        };
        ReservationSelection: {
            candidateId: components["schemas"]["Uuid"];
            resourceIds: components["schemas"]["Uuid"][];
        };
        ReservationPreparationPayload: {
            venueId: components["schemas"]["Uuid"];
            partySize: number;
            requestedRange: components["schemas"]["TimeRange"];
            selection: components["schemas"]["ReservationSelection"];
        };
        ReservationPreparationRequest: components["schemas"]["CommandEnvelope"] & {
            contract?: {
                /** @constant */
                contractId: "C04";
                /** @constant */
                contractVersion: "2.0.0";
            };
            /** @constant */
            commandType?: "PREPARE_RESERVATION";
            payload?: components["schemas"]["ReservationPreparationPayload"];
        };
        TableGroupSnapshot: {
            groupId: components["schemas"]["Uuid"];
            groupVersion: number;
            resourceIds: components["schemas"]["Uuid"][];
        };
        Digest: string;
        /** @description Opaque authenticated transport token; clients MUST NOT decode it */
        ConfirmationToken: string;
        Preparation: {
            preparationId: components["schemas"]["Uuid"];
            tenantId: components["schemas"]["Uuid"];
            venueId: components["schemas"]["Uuid"];
            partySize: number;
            requestedRange: components["schemas"]["TimeRange"];
            resolvedResourceSnapshot: components["schemas"]["TableGroupSnapshot"];
            policyVersionIds: components["schemas"]["Uuid"][];
            termsDigest: components["schemas"]["Digest"];
            termsArtifact: string;
            createdAt: components["schemas"]["Instant"];
            expiresAt: components["schemas"]["Instant"];
            /** @enum {unknown} */
            status: "OPEN" | "CONSUMED" | "EXPIRED" | "REVOKED";
            confirmationToken: components["schemas"]["ConfirmationToken"];
        };
        AcceptedTerms: {
            policyVersionId: components["schemas"]["Uuid"];
            termsDigest: string;
            acceptedAt: components["schemas"]["Instant"];
            acceptedBy: components["schemas"]["Actor"];
            /** @enum {unknown} */
            acceptanceChannel?: "WEB" | "STAFF" | "API";
        };
        ReservationConfirmationPayload: {
            confirmationToken: components["schemas"]["ConfirmationToken"];
            acceptedTerms: components["schemas"]["AcceptedTerms"][];
        };
        ReservationConfirmationRequest: components["schemas"]["CommandEnvelope"] & {
            contract?: {
                /** @constant */
                contractId: "C04";
                /** @constant */
                contractVersion: "2.0.0";
            };
            /** @constant */
            commandType?: "CONFIRM_RESERVATION";
            payload?: components["schemas"]["ReservationConfirmationPayload"];
        };
        OperationResult: {
            /** @constant */
            ok: true;
            correlationId: components["schemas"]["Uuid"];
            contract: components["schemas"]["ContractRef"];
            result: unknown;
        } | {
            /** @constant */
            ok: false;
            correlationId: components["schemas"]["Uuid"];
            contract: components["schemas"]["ContractRef"];
            error: components["schemas"]["Error"];
        };
        Reservation: {
            reservationId: components["schemas"]["Uuid"];
            tenantId: components["schemas"]["Uuid"];
            venueId: components["schemas"]["Uuid"];
            /** @enum {unknown} */
            status: "CONFIRMED" | "CANCELLED" | "COMPLETED" | "NO_SHOW";
            version: number;
            partySize: number;
            timeRange: components["schemas"]["TimeRange"];
            occupiedRange: components["schemas"]["TimeRange"];
            resources: components["schemas"]["AtomicResource"][];
            acceptedTerms: components["schemas"]["AcceptedTerms"][];
            createdAt: components["schemas"]["Instant"];
            updatedAt: components["schemas"]["Instant"];
        };
        ExpectedVersionCommand: {
            expectedVersion: number;
            ifMatchVersion: number;
        };
    };
    responses: {
        /** @description Not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Allocation or state conflict (409) */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Stale or disagreeing version (412) */
        PreconditionFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Semantic validation failed (422) */
        Unprocessable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Expected version or If-Match absent (428) */
        PreconditionRequired: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        ReservationId: string;
        IdempotencyKey: string;
        /** @description Strong ETag version; MUST equal body expectedVersion */
        IfMatch: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    searchAvailability: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AvailabilitySearchRequest"];
            };
        };
        responses: {
            /** @description Advisory candidates */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvailabilityResult"];
                };
            };
            422: components["responses"]["Unprocessable"];
        };
    };
    prepareReservation: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReservationPreparationRequest"];
            };
        };
        responses: {
            /** @description Preparation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Preparation"];
                };
            };
            409: components["responses"]["Conflict"];
            422: components["responses"]["Unprocessable"];
        };
    };
    confirmReservation: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReservationConfirmationRequest"];
            };
        };
        responses: {
            /** @description Confirmation result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationResult"];
                };
            };
            409: components["responses"]["Conflict"];
            422: components["responses"]["Unprocessable"];
        };
    };
    getReservation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ReservationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reservation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reservation"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    modifyReservation: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description Strong ETag version; MUST equal body expectedVersion */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                id: components["parameters"]["ReservationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExpectedVersionCommand"];
            };
        };
        responses: {
            /** @description Modified reservation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reservation"];
                };
            };
            409: components["responses"]["Conflict"];
            412: components["responses"]["PreconditionFailed"];
            422: components["responses"]["Unprocessable"];
            428: components["responses"]["PreconditionRequired"];
        };
    };
    cancelReservation: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description Strong ETag version; MUST equal body expectedVersion */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                id: components["parameters"]["ReservationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExpectedVersionCommand"];
            };
        };
        responses: {
            /** @description Cancelled reservation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reservation"];
                };
            };
            409: components["responses"]["Conflict"];
            412: components["responses"]["PreconditionFailed"];
            422: components["responses"]["Unprocessable"];
            428: components["responses"]["PreconditionRequired"];
        };
    };
}
