import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import test from 'node:test';import {diningMapPositions,guestDiningMapMarkup,guestDiningMapModel} from '../src/guest-dining-map.js';import{setDiningPlacementVisible}from'../src/dining-placement-state.js';
const projection=count=>({status:'CONFIRMED',allocationEstablished:true,venueName:'Basil House',partySize:2,timeRange:{start:'2026-10-05T12:00:00.000Z'},tables:Array.from({length:count},(_,i)=>({tableKey:`opaque-${i}`,label:`Table ${String(i+1).padStart(2,'0')}`,capacity:2+i,isYours:i===count-1}))});
for(const count of [2,3,4,5])test(`${count}-table constellation highlights exactly one authority allocation`,()=>{const model=guestDiningMapModel(projection(count));assert.equal(model.tables.length,count);assert.equal(model.tables.filter(x=>x.isYours).length,1);assert.equal(diningMapPositions(count).length,count);assert.match(guestDiningMapMarkup(model),/YOUR TABLE/)});
test('missing or ambiguous allocation fails closed',()=>{for(const tables of [[{label:'Table 01',isYours:false}],[{label:'Table 01',isYours:true},{label:'Table 02',isYours:true}]]){const model=guestDiningMapModel({status:'CONFIRMED',allocationEstablished:true,tables});assert.equal(model.available,false);assert.equal(model.tables.filter(x=>x.isYours).length,0);assert.doesNotMatch(guestDiningMapMarkup(model),/class="guest-map-table is-yours"/)}});
test('guest markup exposes no opaque/internal identity or other-customer data',()=>{const markup=guestDiningMapMarkup(guestDiningMapModel(projection(3)),{bookingReference:'TK-BASIL-1234',timeLabel:'8:00 PM'});assert.doesNotMatch(markup,/opaque-|resourceId|tenantId|allocationId|reservationId/);assert.doesNotMatch(markup,/other customer|guest name/i)});
test('all 24 authoritative venues use one count-driven capability without Kumo fallback',async()=>{const authority=JSON.parse(await readFile(new URL('../../platform/restaurant-authority.json',import.meta.url)));assert.equal(authority.restaurants.length,24);for(const venue of authority.restaurants){const model=guestDiningMapModel({...projection(venue.capacities.length),venueName:venue.name});assert.equal(model.tables.length,venue.capacities.length);assert.equal(model.venueName,venue.name)}assert.doesNotMatch(await readFile(new URL('../src/guest-dining-map.js',import.meta.url),'utf8'),/Kumo Dining|fixture-kumo|10000000-/)});
test('Dining Pass action is confirmation-gated and persisted non-confirmed readback fails closed',async()=>{const source=await readFile(new URL('../src/reservation-experience.js',import.meta.url),'utf8');assert.match(source,/if \(booking\.confirmation\)/);assert.match(source,/data-view-your-table/);assert.match(source,/confirmedReservationRecord\(result\)/);assert.match(source,/if\(!booking\.reservation\)throw/)});
test('confirmed Dining Pass opens authoritative placement without nesting another pass or action',()=>{const reservationShell={hidden:false},placementShell={hidden:true};setDiningPlacementVisible({reservationShell,placementShell},true);assert.equal(reservationShell.hidden,true);assert.equal(placementShell.hidden,false);const markup=guestDiningMapMarkup(guestDiningMapModel(projection(2)),{bookingReference:'TK-KUMO-1234',timeLabel:'9:00 PM'});assert.equal((markup.match(/class="guest-map-table /g)||[]).length,2);assert.equal((markup.match(/YOUR TABLE/g)||[]).length,1);assert.match(markup,/stylized constellation/i);assert.match(markup,/not an exact physical floor plan/i);assert.doesNotMatch(markup,/DINING PASS|VIEW YOUR TABLE|data-view-your-table/i);setDiningPlacementVisible({reservationShell,placementShell},false);assert.equal(reservationShell.hidden,false);assert.equal(placementShell.hidden,true)});
test('responsive and reduced-motion rules constrain the mobile map',async()=>{const css=await readFile(new URL('../src/styles.css',import.meta.url),'utf8');assert.match(css,/@media\(max-width:600px\)/);assert.match(css,/overflow-x:hidden/);assert.match(css,/@media\(prefers-reduced-motion:reduce\)/);assert.match(css,/animation:none!important/)});
