import {navigateRoute,returnCustomerToParent,ROUTES} from './navigation.js';

const landing=document.querySelector('.reference-landing');
const destination=document.createElement('div');destination.className='screen01-destination';destination.innerHTML='<button type="button" data-screen01-back>← Back</button><p></p>';document.body.append(destination);
const showLanding=()=>{const active=location.pathname==='/';const concierge=location.pathname==='/concierge';landing.hidden=!active;destination.hidden=active;document.body.classList.toggle('landing-active',active);document.body.classList.toggle('concierge-active',concierge);destination.querySelector('p').textContent=location.pathname==='/discovery'?'Restaurant discovery':'Concierge';const opening=document.querySelector('#conversation .opening');if(concierge&&opening)opening.innerHTML='<small>TABLEKEEPER · CONCIERGE</small><p>Good evening. I’m Tablekeeper, your dining concierge.<br>What kind of evening are you planning?</p>'};
function enter(path){landing.classList.add('departing');setTimeout(()=>{navigateRoute(path,{state:{screen01:true}});landing.classList.remove('departing')},420)}
document.querySelector('[data-enter-guest]')?.addEventListener('click',()=>enter(ROUTES.CONCIERGE));
document.querySelector('[data-enter-staff]')?.addEventListener('click',()=>enter(ROUTES.STAFF_ACCESS));
addEventListener('popstate',showLanding);addEventListener('tablekeeper:navigate',showLanding);showLanding();
destination.querySelector('[data-screen01-back]').addEventListener('click',returnCustomerToParent);
const intro=document.createElement('section');intro.className='concierge-editorial';intro.innerHTML='<small>AI Concierge</small><h1>Let’s plan<br>your evening.</h1><p>Tell me what you have in mind.<br>I’ll suggest the right restaurants,<br>atmospheres and experiences<br>for you.</p>';document.body.append(intro);
const conciergeLayout=document.createElement('main');conciergeLayout.className='concierge-layout';document.body.append(conciergeLayout);conciergeLayout.append(intro,document.querySelector('.conversation-stage'),document.querySelector('#living-intent'));
const evening=document.createElement('div');evening.className='evening-drawer';evening.hidden=true;evening.innerHTML='<button class="evening-scrim" aria-label="Close"></button><section role="dialog" aria-modal="true" aria-labelledby="evening-heading"><button data-evening-close aria-label="Close">×</button><small>YOUR EVENING</small><h2 id="evening-heading">Your evening is still being planned.</h2><div data-evening-summary></div><button data-continue-planning>Continue planning</button></section>';document.body.append(evening);
function openEvening(){evening.hidden=false;const intent=JSON.parse(sessionStorage.getItem('tablekeeper.concierge.screen01')||'null')?.publicState?.intent;evening.querySelector('[data-evening-summary]').textContent=intent?'I’m keeping what you’ve shared while we plan.':'Tell Tablekeeper what matters and your evening will take shape here.'}
document.addEventListener('click',e=>{if(e.target.closest('[data-evening],.topbar [data-view="evening"]'))openEvening();if(e.target.closest('[data-evening-close],.evening-scrim,[data-continue-planning]'))evening.hidden=true});
const intentPanel=document.querySelector('#living-intent');new MutationObserver(()=>{const row=intentPanel.querySelector('.public-slot:last-of-type');if(!row)return;row.classList.remove('intent-updated');requestAnimationFrame(()=>{row.classList.add('intent-updated');if(!document.body.classList.contains('concierge-active')||matchMedia('(prefers-reduced-motion: reduce)').matches)return;const chamber=document.querySelector('.conversation-stage'),a=chamber?.getBoundingClientRect(),b=row.getBoundingClientRect();if(!a)return;const trace=document.createElement('i');trace.className='intent-transfer-trace';const left=a.right-18,top=Math.min(a.bottom-90,Math.max(a.top+95,b.top+b.height/2));trace.style.cssText=`left:${left}px;top:${top}px;width:${Math.max(28,b.left-left+12)}px`;document.body.append(trace);setTimeout(()=>trace.remove(),900)});setTimeout(()=>row.classList.remove('intent-updated'),900)}).observe(intentPanel,{childList:true,subtree:true});
const composer=document.querySelector('#ask');if(composer)composer.placeholder='Tell me more about your evening…';
