[CmdletBinding()]
param([ValidateSet('Setup','Start','Stop','Status','Reset','ResetAndStart')][string]$Action)

$ErrorActionPreference='Stop'
$root=(Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$settings=Get-Content (Join-Path $PSScriptRoot 'settings.json') -Raw | ConvertFrom-Json
$secretDir=Join-Path $PSScriptRoot 'secrets'; $stateDir=Join-Path $PSScriptRoot 'state'
$stateFile=Join-Path $stateDir 'launcher-state.json'; $logDir=Join-Path $stateDir 'logs'
$psqlFallback='C:\Program Files\PostgreSQL\17\bin\psql.exe'
$pgBin=Split-Path -Parent $psqlFallback;if(!(Test-Path -LiteralPath $psqlFallback)){throw "PostgreSQL 17 psql.exe is unavailable at $psqlFallback"};$env:Path="$pgBin;$env:Path"
function Require-Command($name,$fallback=$null){$cmd=Get-Command $name -ErrorAction SilentlyContinue;if($cmd){return $cmd.Source};if($fallback -and (Test-Path -LiteralPath $fallback)){return $fallback};throw "Required command is unavailable: $name"}
function Read-Secret($name){$path=Join-Path $secretDir $name;if(!(Test-Path -LiteralPath $path)){throw "Missing local secret $name. Run First-time setup."};$value=(Get-Content -LiteralPath $path -Raw).Trim();if(!$value){throw "Local secret $name is empty."};return $value}
function Save-Secret($name,$value){New-Item -ItemType Directory -Force -Path $secretDir|Out-Null;Set-Content -LiteralPath (Join-Path $secretDir $name) -Value $value -Encoding ascii -NoNewline}
function Plain([Security.SecureString]$value){$ptr=[Runtime.InteropServices.Marshal]::SecureStringToBSTR($value);try{[Runtime.InteropServices.Marshal]::PtrToStringBSTR($ptr)}finally{[Runtime.InteropServices.Marshal]::ZeroFreeBSTR($ptr)}}
function Parse-DbUrl($value){try{$uri=[Uri]$value}catch{throw 'Configured database URL is invalid.'};if($uri.Scheme -notin @('postgres','postgresql') -or !$uri.Host){throw 'Configured database URL must be PostgreSQL.'};$db=$uri.AbsolutePath.Trim('/');if(!$db){throw 'Configured database URL has no database name.'};[pscustomobject]@{Uri=$uri;Database=$db;Host=$uri.Host;Port=if($uri.IsDefaultPort){5432}else{$uri.Port}}}
function Load-DatabaseConfig{$bootstrap=Read-Secret 'bootstrap-database-url.txt';$runtime=Read-Secret 'runtime-database-url.txt';$b=Parse-DbUrl $bootstrap;$r=Parse-DbUrl $runtime;if($b.Database -ne $settings.expectedDatabase -or $r.Database -ne $settings.expectedDatabase -or $b.Database -ne $r.Database){throw "Database URL identity mismatch; both must name configured retained database '$($settings.expectedDatabase)'."};if($b.Database -in @('postgres','template0','template1','tablekeeper_integration') -or $b.Database -match 'integration|test'){throw "Refusing protected or disposable database '$($b.Database)'."};[pscustomobject]@{BootstrapUrl=$bootstrap;RuntimeUrl=$runtime;Identity=$r}}
function Invoke-Psql($url,$sql){$psql=Require-Command 'psql' $psqlFallback;& $psql -X -w --dbname $url --set ON_ERROR_STOP=1 --tuples-only --no-align --command $sql;if($LASTEXITCODE -ne 0){throw 'PostgreSQL command failed.'}}
function Assert-Canonical($runtimeUrl){$sql="BEGIN READ ONLY; SELECT set_config('reservation_core.tenant_id','$($settings.tenantId)',true); SELECT (SELECT count(*) FROM reservation_core.venues),(SELECT count(*) FROM reservation_core.table_resources),(SELECT count(*) FROM reservation_core.table_groups),(SELECT count(*) FROM reservation_core.policy_versions),(SELECT count(*) FROM reservation_core.venue_service_hours),(SELECT migration_id FROM reservation_core.schema_migrations ORDER BY migration_id DESC LIMIT 1); ROLLBACK;";$line=(Invoke-Psql $runtimeUrl $sql|Where-Object{$_ -match '^24\|97\|97\|24\|158\|0004_venue_service_hours$'});if(!$line){throw 'Retained demo database failed canonical schema/catalog verification.'}}
function Assert-ResetClean($runtimeUrl){$sql="BEGIN READ ONLY; SELECT set_config('reservation_core.tenant_id','$($settings.tenantId)',true); SELECT (SELECT count(*) FROM reservation_core.reservations),(SELECT count(*) FROM reservation_core.reservation_allocations),(SELECT count(*) FROM reservation_core.preparations),(SELECT count(*) FROM reservation_core.accepted_terms),(SELECT count(*) FROM reservation_core.idempotency_records),(SELECT count(*) FROM reservation_core.domain_audit_records),(SELECT count(*) FROM reservation_core.outbox_events),(SELECT count(*) FROM reservation_core.command_attempts); ROLLBACK;";$line=(Invoke-Psql $runtimeUrl $sql|Where-Object{$_ -match '^0\|0\|0\|0\|0\|0\|0\|0$'});if(!$line){throw 'Reset database retained non-canonical transactional state.'}}
function Is-Listening($port){return [bool](Get-NetTCPConnection -State Listen -LocalPort $port -ErrorAction SilentlyContinue)}
function Load-State{if(Test-Path -LiteralPath $stateFile){Get-Content $stateFile -Raw|ConvertFrom-Json}else{$null}}
function Owned-Process($entry){$p=Get-Process -Id $entry.pid -ErrorAction SilentlyContinue;if(!$p){return $null};if($p.StartTime.ToUniversalTime().ToString('o') -ne $entry.startedAt){return $null};$p}
function Stop-App{$state=Load-State;if(!$state){Write-Host 'Tablekeeper is not running under this launcher.';return};foreach($entry in $state.processes){if(Owned-Process $entry){& taskkill.exe /PID $entry.pid /T /F *> $null;Write-Host "Stopped $($entry.name)."}else{Write-Warning "Skipped stale/unowned PID for $($entry.name)."}};Remove-Item -LiteralPath $stateFile -Force -ErrorAction SilentlyContinue}
function Show-Status{$state=Load-State;if(!$state){Write-Host 'Tablekeeper: STOPPED';return};$all=$true;foreach($entry in $state.processes){$up=[bool](Owned-Process $entry);$all=$all-and$up;Write-Host ("{0}: {1} (PID {2})"-f$entry.name,($(if($up){'RUNNING'}else{'STOPPED'})),$entry.pid)};Write-Host ('Guest: '+$settings.guestUrl);Write-Host ('Staff: '+$settings.staffUrl);if(!$all){Write-Warning 'One or more required services are not running.'}}
function Wait-Http($url,$name){for($i=0;$i -lt 30;$i++){try{$null=Invoke-WebRequest -UseBasicParsing -TimeoutSec 2 $url;return}catch{Start-Sleep -Milliseconds 500}};throw "$name did not become ready at $url"}
function Start-App{
  if(Load-State){Show-Status;throw 'Launcher state already exists. Stop Tablekeeper before starting again.'}
  $db=Load-DatabaseConfig;Require-Command 'node'|Out-Null;Require-Command 'npm.cmd'|Out-Null;$pgReady=Require-Command 'pg_isready' 'C:\Program Files\PostgreSQL\17\bin\pg_isready.exe';
  & $pgReady -h $db.Identity.Host -p $db.Identity.Port -d $db.Identity.Database -t 3 *> $null;if($LASTEXITCODE -ne 0){throw 'PostgreSQL is not reachable.'};Assert-Canonical $db.RuntimeUrl
  New-Item -ItemType Directory -Force -Path $logDir|Out-Null
  $env:RESERVATION_CORE_DATABASE_URL=$db.RuntimeUrl;$env:RESERVATION_CORE_CONFIRMATION_SECRET=Read-Secret 'confirmation-secret.txt';$env:RESERVATION_CORE_DEV_BEARER_TOKEN=Read-Secret 'guest-bearer-token.txt';$env:RESERVATION_CORE_MANAGER_BEARER_TOKEN=Read-Secret 'manager-bearer-token.txt';$env:RESERVATION_CORE_TENANT_ID=$settings.tenantId;$env:RESERVATION_CORE_ACTOR_ID=$settings.guestActorId;$env:RESERVATION_CORE_ACTOR_TYPE='GUEST';$env:RESERVATION_CORE_MANAGER_ACTOR_ID=$settings.managerActorId;$env:RESERVATION_CORE_OPERATIONS_VENUE_ID=$settings.operationsVenueId;$env:RESERVATION_CORE_BASE_URL='http://127.0.0.1:4180';$env:CONCIERGE_BASE_URL='http://127.0.0.1:4310';$env:TABLEKEEPER_STAFF_PIN=Read-Secret 'staff-pin.txt';$env:CONCIERGE_LANGUAGE_PROVIDER='deterministic';$env:CONCIERGE_RETRIEVAL_PROVIDER='local'
  $specs=@(@{name='Reservation Core';file='node';args=@((Join-Path $root 'reservation-core\src\http\server.mjs'));cwd=(Join-Path $root 'reservation-core')},@{name='Frontend + Concierge';file='node';args=@((Join-Path $root 'frontend\start-local.mjs'));cwd=(Join-Path $root 'frontend')});$started=@()
  try{foreach($s in $specs){$safe=$s.name -replace '[^A-Za-z]','-';$p=Start-Process $s.file -ArgumentList $s.args -WorkingDirectory $s.cwd -WindowStyle Hidden -RedirectStandardOutput (Join-Path $logDir "$safe.out.log") -RedirectStandardError (Join-Path $logDir "$safe.err.log") -PassThru;$p.Refresh();$started+=@{name=$s.name;pid=$p.Id;startedAt=$p.StartTime.ToUniversalTime().ToString('o')}};New-Item -ItemType Directory -Force -Path $stateDir|Out-Null;@{startedAt=[DateTime]::UtcNow.ToString('o');processes=$started}|ConvertTo-Json -Depth 4|Set-Content -LiteralPath $stateFile -Encoding utf8;Wait-Http 'http://127.0.0.1:4310/healthz' 'Concierge';Wait-Http $settings.guestUrl 'Frontend';Write-Host 'Tablekeeper is READY.' -ForegroundColor Green;Write-Host ('Guest: '+$settings.guestUrl);Write-Host ('Staff: '+$settings.staffUrl);Start-Process $settings.guestUrl}catch{Stop-App;throw}
}
function Reset-Demo{
  if(Load-State){throw 'Stop Tablekeeper before resetting the demo.'};$db=Load-DatabaseConfig;Write-Host ("Database to RESET: {0} on {1}:{2}" -f $db.Identity.Database,$db.Identity.Host,$db.Identity.Port) -ForegroundColor Yellow;$confirm=Read-Host 'Type RESET to permanently rebuild this retained demo database';if($confirm -cne 'RESET'){throw 'Reset cancelled; confirmation did not match RESET.'}
  $builder=[UriBuilder]$db.BootstrapUrl;$builder.Path='/postgres';$maintenance=$builder.Uri.AbsoluteUri;$name=$db.Identity.Database;Invoke-Psql $maintenance "SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname='$name' AND pid<>pg_backend_pid();"|Out-Null;Invoke-Psql $maintenance "DROP DATABASE $name;"|Out-Null;Invoke-Psql $maintenance "CREATE DATABASE $name;"|Out-Null
  $digest=(Get-FileHash (Join-Path $root 'contracts\releases\2.0.0\contract-registry.json') -Algorithm SHA256).Hash.ToLower();$env:TK_BOOTSTRAP_DATABASE_URL=$db.BootstrapUrl;$migrationOut=Join-Path $stateDir 'reset-migration.json';New-Item -ItemType Directory -Force -Path $stateDir|Out-Null;& (Join-Path $root 'reservation-core\bin\reservation-core.cmd') migrate --mode up --database-url-env TK_BOOTSTRAP_DATABASE_URL --migrations (Join-Path $root 'reservation-core\migrations') --expected-contract-graph-sha256 $digest --output $migrationOut;if($LASTEXITCODE -ne 0){throw 'Migration failed; startup was not attempted.'};$env:TK_DATABASE_URL=$db.RuntimeUrl;$seedOut=Join-Path $stateDir 'reset-seed.json';& (Join-Path $root 'reservation-core\bin\reservation-core.cmd') seed --database-url-env TK_DATABASE_URL --descriptor (Join-Path $root 'reservation-core\fixtures\local-demo\tablekeeper-platform.seed-descriptor.json') --mode apply --output $seedOut;if($LASTEXITCODE -ne 0){throw 'Seed failed; startup was not attempted.'};Assert-Canonical $db.RuntimeUrl;Assert-ResetClean $db.RuntimeUrl;Write-Host 'Canonical Tablekeeper demo restored.' -ForegroundColor Green
}
function Setup-Operator{Write-Host 'One-time local setup. Input is hidden and is never printed.';$bootstrap=Plain (Read-Host 'Bootstrap PostgreSQL URL for retained tablekeeper database' -AsSecureString);$runtime=Plain (Read-Host 'core_runtime PostgreSQL URL for retained tablekeeper database' -AsSecureString);$null=Parse-DbUrl $bootstrap;$null=Parse-DbUrl $runtime;Save-Secret 'bootstrap-database-url.txt' $bootstrap;Save-Secret 'runtime-database-url.txt' $runtime;$rng=[Security.Cryptography.RandomNumberGenerator]::Create();$bytes=New-Object byte[] 32;$rng.GetBytes($bytes);Save-Secret 'confirmation-secret.txt' ([Convert]::ToBase64String($bytes));$rng.GetBytes($bytes);Save-Secret 'guest-bearer-token.txt' ([Convert]::ToBase64String($bytes));$rng.GetBytes($bytes);Save-Secret 'manager-bearer-token.txt' ([Convert]::ToBase64String($bytes));$pin=Plain (Read-Host 'Choose a four-digit Staff PIN' -AsSecureString);if($pin -notmatch '^\d{4}$'){throw 'Staff PIN must be exactly four digits.'};Save-Secret 'staff-pin.txt' $pin;Load-DatabaseConfig|Out-Null;Write-Host 'Local Operator setup saved.' -ForegroundColor Green}
switch($Action){'Setup'{Setup-Operator};'Start'{Start-App};'Stop'{Stop-App};'Status'{Show-Status};'Reset'{Reset-Demo};'ResetAndStart'{Reset-Demo;Start-App}}

